// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhRXYHe9lGY-oQ8bmYbuuO0Kw5XVV5R5k',
    appId: '1:1029960913518:web:29de98b88c3ba75335cc7f',
    messagingSenderId: '1029960913518',
    projectId: 'kishan-468d1',
    authDomain: 'kishan-468d1.firebaseapp.com',
    storageBucket: 'kishan-468d1.firebasestorage.app',
    measurementId: 'G-B7R99Z7072',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcRk1uONcQQvFs0dCxC7WjkQvOVBguNF0',
    appId: '1:1029960913518:android:1a1872d2da7857b735cc7f',
    messagingSenderId: '1029960913518',
    projectId: 'kishan-468d1',
    storageBucket: 'kishan-468d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpYczgljRDscjPereCtKdyJ2h73xoR4v0',
    appId: '1:1029960913518:ios:bcf7a37ad8ec74c535cc7f',
    messagingSenderId: '1029960913518',
    projectId: 'kishan-468d1',
    storageBucket: 'kishan-468d1.firebasestorage.app',
    iosBundleId: 'com.example.kishan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpYczgljRDscjPereCtKdyJ2h73xoR4v0',
    appId: '1:1029960913518:ios:bcf7a37ad8ec74c535cc7f',
    messagingSenderId: '1029960913518',
    projectId: 'kishan-468d1',
    storageBucket: 'kishan-468d1.firebasestorage.app',
    iosBundleId: 'com.example.kishan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhRXYHe9lGY-oQ8bmYbuuO0Kw5XVV5R5k',
    appId: '1:1029960913518:web:d40d5f4641f1241735cc7f',
    messagingSenderId: '1029960913518',
    projectId: 'kishan-468d1',
    authDomain: 'kishan-468d1.firebaseapp.com',
    storageBucket: 'kishan-468d1.firebasestorage.app',
    measurementId: 'G-3M8RP1WFLW',
  );

}